### ISSUE TITLE
Hot module reloading from Docker container

### ISSUE THREAD

**Issue by cameronk** [kriasoft/react-starter-kit#1012]
Hello,

I've been working on setting up RSK to work within a Docker container. I was able to get everything set up correctly, minus the HMR that comes with Webpack. Some files are picked up by the system when they are modified, some are not.

- Editing `/src/content/about.md` produced: `[file changed] build/content/about.md` in the console, but did not hot reload the content. Upon manual refresh, I could see my changes.
- Editing any other javascript file (I tested primarily with `src/components/Header/Header.js`) did *not* result in a message in the console, and page reloads did not reflect the changed components. I had to do a full container restart to see my changes.

My Browsersync settings are set to enable everything, including CodeSync.

Here are my Docker files:

*Dockerfile*
```
FROM node:7.2.0

ENV APPDIR=/app
COPY package.json npm-shrinkwrap.json $APPDIR/

WORKDIR $APPDIR
RUN npm install
RUN npm cache clean

CMD [ "npm", "start" ]
```

*docker-compose.yml*
```
web:
  build: .
  ports:
    - '3000:3000'
    - '3001:3001'
    - '3002:3002'
    - '5000:5000'
  volumes:
    - .:/app
    - /app/node_modules
```

All exposed ports work correctly, the server just doesn't seem to be picking up any changes. Suggestions?

(note: saw mention of adding docker support for this library, I'd be happy to contribute these files if we can get this issue worked out!)
