### ISSUE TITLE
How to import and use local fonts

### ISSUE THREAD

**Issue by unknown075** [kriasoft/react-starter-kit#1276]
I have added the TPHero font in `public` folder and `@font-face` (refer to this old [commit](https://github.com/kriasoft/react-starter-kit/commit/1d89a0e1ec219066d94ccd04a654858875415d4b)) but it does not seem to work.

Could you please help? 
```js 
// webpack
{
  test: /\.(ico|jpg|jpeg|png|gif|eot|otf|webp|svg|ttf|woff|woff2)(\?.*)?$/,
  loader: 'file-loader',
  query: {
    name: isDebug ? '[path][name].[ext]?[hash:8]' : '[hash:8].[ext]',
  },
},
```

```js
// in variable.css

@font-face {
  font-family: 'TPHero';
  font-style: normal;
  font-weight: normal;
  src:
    url('../../../public/fonts/TPHero/TPHero-Bold.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-BoldItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-ExtraBold.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-ExtraBoldItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-Hairline.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-HairlineItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-Light.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-LightItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-Medium.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-MediumItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-Regular.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-RegularItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-SemiBold.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-SemiBoldItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-Super.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-Thin.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-ThinItalic.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-UltraLight.otf') format('otf'),
    url('../../../public/fonts/TPHero/TPHero-UltraLightItalic.otf') format('otf');
}
```
<img height="400" alt="screen shot 2017-05-22 at 10 25 25 pm" src="https://cloud.githubusercontent.com/assets/28875812/26326899/94643792-3f3d-11e7-814a-f32af6c9f49e.png">

**Comment by frenzzy** [comment]
You should not put to variables.css anything except variables, otherwise the code will be duplicated multiple times - depends on how many `@import`s of the `variables.css` file do you have.

The best place for custom fonts is your top level react component (`src/components/Layout/Layout.css` in RSK).

Then you need to define `@font-face` for each font separately. For example `light`, `italic`, `bold` etc. are different fonts. Also it is not recommended to import more than 2-3 fonts per page - it it too heavy.

About path to fonts, you can use the same modular/component approach here, just put them to the components folder and use relative path in `url(./fonts/font-name.ext)`, but if you want save font-file name on production, put them to `public/fonts/font-name.ext` folder and use absolute path in css `url(/fonts/font-name.ext)`.

Example:
```bash
/src/component/Layout/
├── /fonts/
│   ├── /Roboto-Regular.woff2
│   ├── /Roboto-Regular.woff
│   ├── /Roboto-Bold.woff2
│   └── /Roboto-Bold.woff
├── Layout.css
├── Layout.js
└── package.json
```
```css
/* src/components/Layout/Layout.css */
@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 400;
  src:
    local('Roboto'),
    local('Roboto-Regular'),
    url(./fonts/Roboto-Regular.woff2) format('woff2'),
    url(./fonts/Roboto-Regular.woff) format('woff');
}

@font-face {
  font-family: 'Roboto';
  font-style: normal;
  font-weight: 700;
  src:
    local('Roboto Bold'),
    local('Roboto-Bold'),
    url(./fonts/Roboto-Bold.woff2) format('woff2'),
    url(./fonts/Roboto-Bold.woff) format('woff');
}

html {
  font-family: 'Roboto', sans-serif;
}

/* ... */
```
