### ISSUE TITLE
Travis Auto Deployment

### ISSUE THREAD

**Issue by atalebagha** [kriasoft/react-starter-kit#1371]
Has anyone had success auto deploying this repo using travis.

I want to auto deploy changes to master branch on our git to heroku using travis.  Any help would be appreciated.

**Comment by frenzzy** [comment]
You must deploy only the content of the `build` folder.

[Travis CI -> Heroku Deployment](https://docs.travis-ci.com/user/deployment/heroku/)
[CircleCI -> Continuous Deployment with Heroku](https://circleci.com/docs/1.0/continuous-deployment-with-heroku/)
[Heroku -> GitHub Integration -> Automatic deploys](https://devcenter.heroku.com/articles/github-integration#automatic-deploys)

Also you may automatically run `yarn run deploy` with configured Heroku deployment inside CI scripts. Demo: https://frenzzy.herokuapp.com/

**Comment by goldylucks** [comment]
@frenzzy I'm using travis like this:

```yml
before_deploy: yarn global add babel-cli babel-core && yarn add --dev babel-preset-env babel-preset-flow babel-preset-react babel-preset-stage-2

deploy:
  provider: script
  script: yarn deploy

```

**Comment by frenzzy** [comment]
Maybe you must use `yarn install --production=false` instead to install all `devDependencies` which are necessary for `deploy` script.

**Comment by goldylucks** [comment]
@frenzzy what are you using in that demo project?

**Comment by frenzzy** [comment]
I manually run `yarn run deploy` to push the content of the build folder to `deployment` branch.
On Heroku side automatic deploys are configured from this branch.

**Comment by goldylucks** [comment]
Yea I'm doing that too, but this entire thread is specifically about travis

**Comment by goldylucks** [comment]
@frenzzy the configuration ...

```yml
before_deploy: yarn install --production=false

deploy:
  provider: script
  script: yarn deploy

```

... still yields same error:

```sh
$ babel-node tools/run deploy
sh: 1: babel-node: not found
error Command failed with exit code 127.
```

**Comment by frenzzy** [comment]
Maybe  need to use [install or before install](https://docs.travis-ci.com/user/customizing-the-build/#The-Build-Lifecycle) section?
```yml
install:
  - yarn install --production=false
```
or maybe yarn version on travis ci does not support this flag and need to manually install the latest version of yarn as described [here](https://docs.travis-ci.com/user/languages/javascript-with-nodejs#Travis-CI-supports-yarn).

**Comment by goldylucks** [comment]
DONE!

@frenzzy I can prepare a PR of a recipe how to do that, and refer this issue for closing :)

```yml
language: node_js
node_js: node
script: yarn fix
branches:
  only:
  - master
  - "/v\\d\\./"
cache:
  directories:
  - node_modules

before_deploy: yarn build -- --release && cd build && git init && git add . && git commit -m "update build"

deploy:
  provider: heroku
  app: adamgoldman-starter-kit
  api_key:
    secure: PUoxBRGFnTAz5Eo6zdmj7SRnagwsB03OcSd/rcbKjeOApQygAvhCbbo0W0s76zVJfU8yEsWEAs8GIvHQui0FwNDiDXBoifMD5BTT6ITgjlECK6cVEgB0EqzxBb93qsTouxy9CRF8uZ4dgGkNsiff8NFkHiEuLbIY90WYxkJerST80qTcpWus9qrgbQH/nGEFhPSM04FAllM9LpQJkXNrUODONCfj9VUEKXNoRQ1X1IASCcbkLL23dv6uK+tywurw3ivSMaGQ+371KIMJZVGbjDF/5nd+bYQep8NtW3C35W1IV0bOlflaoaNF7gzd5dw8BlPTfGAAtJ7PdnOZtIiAtvqp2XbbNuTQwisF4z0MXtg9oY5+3YLsoMoImm3lf39vrDlDB4PDLybxOESck4OPXcSYkgKehQdmqjNcEJJvQraQngkh/Fw3k7DysyrGUM+kbtcHkEWLWKnWClqRQCLu/sWQfk+TAlYVuV5ARcq9iUjLBNpt7VYNS8tvEIEw4rSkQIt17jeUPpWPu1eNx6hO/lBkMJlLCHLCr37GdzZ3uiuRM50HBeY7epoKGsM1khcdZ7kvrl6r2RI02oZ5Rfagk7fxCjzByAJD2ZbCu/IEkAcXu3I9kXYer4AQ+q58QACri41TqJr2YOepCG65JPXR5vFyifKgjrjg7jaevmjVAJY=
```

**Comment by frenzzy** [comment]
Interesting solution... 👍  Yes, a PR with a recipe would be awesome! Thanks

**Comment by goldylucks** [comment]
@frenzzy turns out it's much simpler than that on heroku.

the solution I posted above will work for any provider, but for heroku, it's enough to do:

```yml
# .travis.yml
deploy:
  provider: heroku
  app: adamgoldman-starter-kit
  api_key:
    secure: API_KEY
```
```
# Procfile
web: node build/server
```
and the heroku ENV variables:
```
HEROKU_URL: https://adamgoldman-starter-kit.herokuapp.com
NODE_ENV: production
NPM_CONFIG_PRODUCTION: false
```

I think for heroku, the latter approach "smells" better, but it might be useful to log the workaround I did at first, in case their would be trouble with other providers.

What do you think?
