### ISSUE TITLE
require image in CSS

### ISSUE THREAD

**Issue by cwtuan** [kriasoft/react-starter-kit#322]
In header.jsx, we can require a image like,

```
<img className="Header-brandImg" src={require('./logo-small.png')} />
```

Is it possible to require a image in CSS? Something like:

```
.HomePage-container H1:before {
  content: url({require('/images/test.png')});
}
```
##

**Comment by luqin** [comment]
```css
.HomePage-container H1:before {
  content: url('somemodule/images/test.png'); // from node_modules/somemodule
}
```
