### ISSUE TITLE
How to handle CSS media queries?

### ISSUE THREAD

**Issue by kpnigalye** [kriasoft/react-starter-kit#350]
how to use media queries with .scss file?
##

**Comment by Bogdaan** [comment]
@kpnigalye see http://sass-lang.com/documentation/file.SASS_REFERENCE.html#media

**Comment by frenzzy** [comment]
RSK uses [precss](https://github.com/jonathantneal/precss), so you can see which postcss plugins there included and look at their docs, for example:

- [postcss-custom-media](https://github.com/postcss/postcss-custom-media): W3C custom media queries

  ```css
  @custom-media --small-viewport (max-width: 30em);

  @media (--small-viewport) {
    /* styles for small viewport */
  }
  ```

- [postcss-media-minmax](https://github.com/postcss/postcss-media-minmax): W3C `<` `<=` `>=` `>` media queries

  ```css
  @media screen and (width >= 500px) and (width <= 1200px) {
    .bar {
      display: block;
    }
  }
  ```
