### ISSUE TITLE
Composes (css modules) not works

### ISSUE THREAD

**Issue by Geoide** [kriasoft/react-starter-kit#363]
Anyone else?
##

**Comment by Bogdaan** [comment]
@Geoide can you provide more information?

**Comment by frenzzy** [comment]
From [CSS Modules Composition](https://github.com/css-modules/css-modules#composition) docs:
> There can be multiple composes rules, but composes rules must be before other rules. **Extending works only for local-scoped selectors and only if the selector is a single class name.** When a class name composes another class name, the CSS Module exports both class names for the local class. This can add up to multiple class names.

maybe you are using `composes` inside nesting or selector contain not only classname?
```css
/* wrong */
@media (min-width: 500px) {
  .classNameA { color: red; }
  .classNameB { composes: classNameA; }
}

/* wrong */
.classNameA div { color: red; }
.classNameB { composes: classNameA; }

/* ok */
.classNameA { color: red; }
.classNameB { composes: classNameA; }
```
