### ISSUE TITLE
How to access `App.scss` styles in other components?

### ISSUE THREAD

**Issue by vishalvijay** [kriasoft/react-starter-kit#395]
Does styes in `App.scss` is meant to be used in other components?

Pervious version of starter kit, I was able use styles defined in `App.scss` in all other component (as global style). But after [this commit](https://github.com/kriasoft/react-starter-kit/commit/66e2ef657f105b5d39e635fa7be76097d496eb10#diff-be5bcbffb67f29d9a5b5d57f8e1e6eb3) everything changed, any solution?

**Comment by frenzzy** [comment]
It would be better to keep the styles of components isolated from each other. For example [Shadow DOM](https://www.w3.org/TR/shadow-dom/), [BEM](https://en.bem.info/method/) and [CSS Modules](https://github.com/css-modules/css-modules) invented specifically to solve this problem.

So, what styles you want to reuse?

However, you can:

1. Use [CSS Import](https://www.w3.org/TR/css-cascade-3/#at-import) for shared code, example (see also [precss](https://github.com/jonathantneal/precss) features):

  ```css
  @import '../variables.css'; /* :root { --color: red; } */

  .className {
    color: var(--color);
  }
  ```

2. Use [CSS Modules Dependencies](https://github.com/css-modules/css-modules#dependencies), example:

  ```css
  .otherClassName {
    composes: className from '../SomeComponent/SomeComponent.css';
  }
  ```

3. Use [CSS Modules Global Scope](https://github.com/css-modules/css-modules#exceptions), example:

  ```css
  .localClassName { /* will be transformed to a hash like .abc5436 */
    color: green;
  }
  :global(.globalClassName) { /* will keep class name globally .globalClassName */
    color: red;
  }
  ```
