### ISSUE TITLE
Docker problem: Unwanted files

### ISSUE THREAD

**Issue by sauravskumar** [kriasoft/react-starter-kit#828]
Adding a docker file

```
version: '2'

services:
  support:
    build: .
    image: sauravskumar/support
    container_name: support
    command: bash -c "npm start"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

    ports:
      - 3000:3000
      - 3001:3001
      - 3002:3002
      - 3030:3030
    environment:
        NODE_ENV: development
```

[screenshot - see red files in the project view](http://i.imgur.com/FdEqqIZ.png)
leads to a lot of unwanted files in the root directory of the project... can some one tell what i am missing out..

---

Used to use the same docker file with this project and it worked totally fine with it...
## [react-redux-hot](https://github.com/erikras/react-redux-universal-hot-example)

UPDATE:
updated image link
